USE [s17guest26]
GO

INSERT INTO [dbo].[States]
           ([stateName])
     VALUES
('Oregon'),
('British Columbia'),
('Queensland'),
('Oregon'),
('England'),
('California'),
('Oregon'),
('New South Wales'),
('California'),
('California'),
('New South Wales'),
('Washington'),
('England'),
('Maryland'),
('California'),
('British Columbia'),
('Washington'),
('England'),
('British Columbia'),
('California'),
('Washington'),
('England'),
('California'),
('Washington'),
('New South Wales'),
('California'),
('Oregon'),
('California'),
('England'),
('Washington'),
('Oregon'),
('California'),
('Oregon'),
('England'),
('California'),
('New South Wales'),
('Oregon'),
('New South Wales'),
('England'),
('Ohio'),
('California'),
('Queensland'),
('New South Wales'),
('Queensland'),
('Washington'),
('New South Wales'),
('New South Wales'),
('Washington'),
('England'),
('Washington'),
('California'),
('Washington'),
('California'),
('California'),
('British Columbia'),
('England'),
('California'),
('California'),
('Washington'),
('Washington'),
('New South Wales'),
('Washington'),
('California'),
('New South Wales'),
('California'),
('New South Wales'),
('Washington'),
('Oregon'),
('Washington'),
('England'),
('Alberta'),
('Queensland'),
('California'),
('England'),
('Queensland'),
('Washington'),
('Victoria'),
('Washington'),
('Victoria'),
('California'),
('Washington'),
('Washington'),
('England'),
('New South Wales'),
('England'),
('California'),
('Washington'),
('New South Wales'),
('California'),
('British Columbia'),
('California'),
('New South Wales'),
('British Columbia'),
('California'),
('British Columbia'),
('British Columbia'),
('California'),
('Oregon'),
('New South Wales'),
('British Columbia')


GO


